language:
  python
python:
  2.7
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
  - PLONE_VERSION=5.1.x
  - PLONE_VERSION=5.2.x
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true

cache:
  pip: true
  directories:
  - eggs
  - downloads
  - $HOME/buildout-cache
before_install:
# install chrome webdriver
  - mkdir webdriver;
    wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz;
    tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C webdriver;
    wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip;
    unzip chromedriver_linux64.zip -d webdriver;
    export PATH=$PATH:$(pwd)/webdriver;
  - pip2.7 install popt || pip2.7 install --user  popt
install:
  #- sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  #- sed -ie "s#buildout.cfg#test-$PLONE_VERSION.cfg#" travis.cfg
  - mkdir -p buildout-cache/{downloads,eggs}
  # - python bootstrap.py -c travis.cfg
  - ./bootstrap.sh test-$PLONE_VERSION.cfg
  - bin/buildout -c test-$PLONE_VERSION.cfg -N
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export ROBOT_BROWSER=chrome"
script:
  - bin/test
  - grep  --include=output.xml -Rl  FAIL parts/test | xargs --no-run-if-empty -n 1 popt
after_success:
  - test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
