name: tests

on:
  push:
    branches: [ master, python3 ]
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["2.7",   "plone52-py27"]
        - ["3.6",   "plone52-py36"]
        - ["3.7",   "plone52-py37"]
        - ["3.8",   "plone52-py38"]
        - ["3.7",   "plone60-py37"]
        - ["3.8",   "plone60-py38"]
        - ["3.9",   "plone60-py39"]
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - uses: nanasess/setup-chromedriver@master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
